tweak env checks, update SDK version

diff --git a/usr/bin/bigquery-export b/usr/bin/bigquery-export
--- a/usr/bin/bigquery-export
+++ b/usr/bin/bigquery-export
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 set -e
+set -x
 
 exec 200< $0
 if ! flock -n 200; then echo "OK: There can be only one query process happening at once. Exit" && exit 1; fi
@@ -20,12 +21,22 @@ START=$(date -d${DSTART} +%s)
 END=$(date -d${DEND} +%s)
 CUR=${START}
 
+# Check if CRON is being used. We set a "lock" file for run times
 if test -n "${GOOGLE_CLOUDSDK_CRONFILE}"; then
     # Check if the process should run or not.
     if [[ -f "/tmp/runjob.txt" ]]; then echo "OK: Time to run export process..."; else echo "INFO: No export job is present. Exit" && exit 1; fi
 else
     echo "OK: Cron is not present"
 fi
+
+# Check is the passed SQL is present.
+if [[ -f "/sql/${GOOGLE_GOOGLE_BIGQUERY_SQL}.sql" ]]; then
+  echo "OK: The ${GOOGLE_GOOGLE_BIGQUERY_SQL} is present. Ready to run..."
+else
+  echo "ERROR: The is no ${GOOGLE_GOOGLE_BIGQUERY_SQL} present. Can not run without ${GOOGLE_GOOGLE_BIGQUERY_SQL} being present. Please check your configs."
+  exit 1
+fi
+
 
 function setup_gs_storage() {
 
@@ -53,7 +64,7 @@ function setup_bq_tables() {
   # We will archive our processed data for audting purposes for 30 days
 
   GOOGLE_BIGQUERY_WD_DATASET="${GOOGLE_BIGQUERY_JOB_DATASET}_wd"
-  GOOGLE_BIGQUERY_ARCHIVE_DATASET="${GOOGLE_BIGQUERY_JOB_DATASET}_archive"
+  GOOGLE_BIGQUERY_ARCHIVE_DATASET="${GOOGLE_BIGQUERY_JOB_DATASET}_ARCHIVE"
 
   if ! bq ls -d | grep -q "${GOOGLE_BIGQUERY_JOB_DATASET}_wd"; then
      echo "OK: ${GOOGLE_BIGQUERY_JOB_DATASET}_wd does not exist. Creating..."
@@ -62,11 +73,11 @@ function setup_bq_tables() {
      echo "INFO: ${GOOGLE_BIGQUERY_JOB_DATASET}_WD dataset already exists"
   fi
 
-  if ! bq ls -d | grep -q "${GOOGLE_BIGQUERY_JOB_DATASET}_archive"; then
-     echo "OK: ${GOOGLE_BIGQUERY_JOB_DATASET}_archive does not exist. Creating..."
+  if ! bq ls -d | grep -q "${GOOGLE_BIGQUERY_JOB_DATASET}_ARCHIVE"; then
+     echo "OK: ${GOOGLE_BIGQUERY_JOB_DATASET}_ARCHIVE does not exist. Creating..."
      bq mk --default_table_expiration 2678400 "${GOOGLE_BIGQUERY_ARCHIVE_DATASET}"
   else
-     echo "INFO: ${GOOGLE_BIGQUERY_JOB_DATASET}_archive dataset already exists."
+     echo "INFO: ${GOOGLE_BIGQUERY_JOB_DATASET}_ARCHIVE dataset already exists."
   fi
 
   #Import the query and set the required BQ variables
@@ -135,7 +146,7 @@ function archive_table() {
      # Make sure we dont copy test tables
      for i in $(bq ls -n 9999 "${GOOGLE_CLOUDSDK_CORE_PROJECT}" | grep "testing_*" | awk '{print $1}'); do bq rm -ft "${GOOGLE_CLOUDSDK_CORE_PROJECT}"."${i}"; done
      # Transfer to archive dataset
-     bq cp "${GOOGLE_CLOUDSDK_CORE_PROJECT}":"${GOOGLE_BIGQUERY_WD_DATASET}"."${FILEDATE}"_"${GOOGLE_GOOGLE_BIGQUERY_SQL}" "${GOOGLE_CLOUDSDK_CORE_PROJECT}":"${GOOGLE_BIGQUERY_ARCHIVE_DATASET}"."${FILEDATE}"_"${GOOGLE_GOOGLE_BIGQUERY_SQL}"_archive
+     bq cp "${GOOGLE_CLOUDSDK_CORE_PROJECT}":"${GOOGLE_BIGQUERY_WD_DATASET}"."${FILEDATE}"_"${GOOGLE_GOOGLE_BIGQUERY_SQL}" "${GOOGLE_CLOUDSDK_CORE_PROJECT}":"${GOOGLE_BIGQUERY_ARCHIVE_DATASET}"."${FILEDATE}"_"${GOOGLE_GOOGLE_BIGQUERY_SQL}"_ARCHIVE
    else
      echo "Ok: No Table Archive. Running in TEST mode"
   fi
